#######
# Cloudify Blueprint which describes a xap cluster (single node)
#
imports:
     -  http://www.getcloudify.org/spec/cloudify/3.0/types.yaml
     -  http://www.getcloudify.org/spec/bash-plugin/1.0/plugin.yaml

plugins:
    xap_config_plugin:
        derived_from: cloudify.plugins.agent_plugin
        properties:
            folder: xap-config-plugin

types:
    xap_node:
        derived_from: cloudify.types.bash.app_server
        properties:
            - GSA_JAVA_OPTS: ""
            - gsm_cnt: 0
            - global_gsm_cnt: 0
            - GSM_JAVA_OPTS: ""
            - lus_cnt: 0
            - lus_port: 0
            - LUS_JAVA_OPTS: ""
            - global_lus_cnt: 0
            - gsc_cnt: 0
            - GSC_JAVA_OPTS
            - download_url: "http://repository.cloudifysource.org/com/gigaspaces/xap-core/10.0.0-11600-RELEASE/gigaspaces-xap-premium-10.0.0-ga-b11600.zip"
            - license_key: "Aug 20, 2016~DeWayneFilppi_GigaSpaces@ORwOOYpbOeORmVZZlBQh#PREMIUM^10.0XAPPremium%UNBOUND+UNLIMITED//WAN//EMT"
            - scripts:
                create: xap-scripts/install-xap.sh
                start: xap-scripts/start-xap.sh
                stop: xap-scripts/stop-xap.sh

    demo_shell:
        derived_from: cloudify.types.bash.web_server
        properties:
            - butterfly_repo: https://github.com/yohanakh/butterfly.git
            - demo_url: https://dl.dropboxusercontent.com/u/27248132/DemoScript.zip
            - ui_port: 8888

relationships:
    xap_connected_to_lus:
        derived_from: cloudify.relationships.connected_to
        source_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                - postconfigure: xap_config_plugin.tasks.get_locator
     
blueprint:
    name: xap
    nodes:
        -   name: xap_mgmt_vm
            type: cloudify.types.host
            properties:
                ip: 127.0.0.1
                cloudify_agent:
                    key: /home/vagrant/.ssh/id_rsa
                    user: vagrant

        -   name: xap_container_vm
            type: cloudify.types.host
            properties:
                ip: 127.0.0.1
                cloudify_agent:
                    key: /home/vagrant/.ssh/id_rsa
                    user: vagrant

        -   name: xap_mgmt
            type: xap_node
            properties:
                lus_cnt: 1
                gsm_cnt: 1
                GSC_JAVA_OPTS: -Xms128m -Xmx128m
            relationships:
                -   target: xap_mgmt_vm
                    type: cloudify.relationships.contained_in

        -   name: interactive_shell
            type: demo_shell
            properties:
                scripts:
                    create: butterfly-scripts/install.sh
                    start:  butterfly-scripts/start.sh
#                    stop:   butterfly-script/stop.sh
            relationships:
                -   target: xap_mgmt_vm
                    type: cloudify.relationships.contained_in
                -   target: xap_mgmt
                    type: cloudify.relationships.depends_on

        -   name: webui
            type: cloudify.types.bash.web_server
            properties:
                scripts:
                    start: xap-scripts/start-ui.sh
            relationships:
                -   target: xap_mgmt_vm
                    type: cloudify.relationships.contained_in
                -   target: xap_mgmt
                    type: cloudify.relationships.depends_on

        -   name: sample-space
            type: cloudify.types.bash.app_module
            properties:
                scripts:
                    start: xap-scripts/deploy-demo-space.sh
            relationships:
                -   target: xap_mgmt_vm
                    type: cloudify.relationships.contained_in
                -   target: xap_mgmt
                    type: cloudify.relationships.depends_on
            
        -   name: xap_container
            type: xap_node
            properties:
                gsc_cnt: 1
                GSC_JAVA_OPTS: -Xms128m -Xmx128m
            relationships:
                -   target: xap_container_vm
                    type: cloudify.relationships.contained_in
                -   target: xap_mgmt
                    type: xap_connected_to_lus
